### PR TITLE
🔧 add nygc to sequencing centers and scRNA seq experiment strategy

### PR DESCRIPTION
**Pull request by calkinsh**
add New York Genome Center to sequencing center constants

### CODE REVIEW

**Review by znatty22 — APPROVED** [review]
I'm assuming this sequencing center was already added to the dataservice with that KF ID?

**Comment by znatty22** [comment]
@calkinsh I didn't see the linter failed. I think you have to run `black --line-length 80 kf_lib_data_ingest` to automatically fix it or you can try replacing your single quotes with double quotes to see if that fixes it

**Comment by chris-s-friedman** [comment]
I think the line length error is separate from this PR. [CSIR  sequencing center name ](https://github.com/kids-first/kf-lib-data-ingest/blob/b487540d132bd7da94dc5823951a4f2860383b5e/kf_lib_data_ingest/common/constants.py#L203)violates line length rule.

**Review by znatty22 — COMMENTED** [review]
👍

**Pull request merged**
