### PR TITLE
🐛 Family ID is optional for Participants

### LINKED ISSUE #488: Load Stage Failure on Participant Entity when Family ID is not assigned
When attempting to load participants in an ingest package without family relationship entities, the load stage fails with this error: 

assert None is not record[CONCEPT.FAMILY.ID]

The Load stage appears to require Family ID for loading participants even though family entities are not being created. Here is the ingest log from Chris Friedman's project (he ran into the issue most recently):

2020-09-09 17:01:16,704 - LoadStage - Thread: MainThread - INFO - Begin loading participant
2020-09-09 17:01:16,709 - DataIngestPipeline - Thread: MainThread - ERROR - 'FAMILY|ID'
Traceback (most recent call last):
  File "/Users/friedmanc1/Documents/ingest/kf-ingest-packages/venv/lib/python3.8/site-packages/kf_lib_data_ingest/etl/ingest_pipeline.py", line 259, in run
    output = stage.run(output)
  File "/Users/friedmanc1/Documents/ingest/kf-ingest-packages/venv/lib/python3.8/site-packages/kf_lib_data_ingest/common/stage.py", line 118, in wrapper
    r = func(instance, *args, **kwargs)
  File "/Users/friedmanc1/Documents/ingest/kf-ingest-packages/venv/lib/python3.8/site-packages/kf_lib_data_ingest/common/stage.py", line 165, in run
    output = self._run(*args, **kwargs)
  File "/Users/friedmanc1/Documents/ingest/kf-ingest-packages/venv/lib/python3.8/site-packages/kf_lib_data_ingest/etl/load/load.py", line 372, in _run
    payload = entity_class.build_entity(
  File "/Users/friedmanc1/Documents/ingest/kf-ingest-packages/venv/lib/python3.8/site-packages/kf_lib_data_ingest/target_api_plugins/kids_first_dataservice.py", line 133, in build_entity
    "family_id": get_target_id_from_record(Family, record),
  File "/Users/friedmanc1/Documents/ingest/kf-ingest-packages/venv/lib/python3.8/site-packages/kf_lib_data_ingest/etl/load/load.py", line 214, in _get_target_id_from_record
    entity_class.class_name, entity_class.build_key(record)
  File "/Users/friedmanc1/Documents/ingest/kf-ingest-packages/venv/lib/python3.8/site-packages/kf_lib_data_ingest/target_api_plugins/kids_first_dataservice.py", line 101, in build_key
    assert None is not record[CONCEPT.FAMILY.ID]
KeyError: 'FAMILY|ID'
2020-09-09 17:01:16,711 - DataIngestPipeline - Thread: MainThread - INFO - Exiting.

### PR DESCRIPTION
**Pull request by fiendish**
closes #488

### CODE REVIEW

**Comment by fiendish** [comment]
@nicholasvk @chris-s-friedman , can y'all test this?

**Review by chris-s-friedman — APPROVED** [review]
tested it with @abgeorge7's ingest package that we're developing. @ https://github.com/kids-first/kf-ingest-packages/commit/9059023d530ca5519a9fb50762b5b39624342a41 we just ingest participant id only (no family id... or anything else). the ingest lib throws no errors :)

**Review by znatty22 — APPROVED** [review]
✅

**Comment by fiendish** [comment]
> throws no errors

Ok but does it work? :)

**Comment by chris-s-friedman** [comment]
the ingest ran successfully into qa. in the qa dtaservice, family link is `null`

@youngnm does it look good in qa postgres?

**Comment by fiendish** [comment]
great

**Pull request merged**
