### PR TITLE
📝 Consolidate example extract config copies

### PR DESCRIPTION
**Pull request by fiendish**

### CODE REVIEW

**Comment by chris-s-friedman** [comment]
Now that i'm thinking about it - does `from kf_lib_data_ingest.etl.extract.operations import *` automatically import `Split` because of https://github.com/kids-first/kf-lib-data-ingest/blob/master/kf_lib_data_ingest/etl/extract/operations.py#L17-L21 ?

**Comment by fiendish** [comment]
Yes but I don't mind

**Comment by fiendish** [comment]
honestly, my linter even complains about importing * instead of explicit entries, but I'm ok with it

**Review by chris-s-friedman — APPROVED** [review]
👍

**Pull request merged**
